version: '3.8'

services:
  review-db:
    image: mysql:8.4.3
    container_name: review-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ReviewsDB
    restart: always
